#!/bin/bash
#
## Cool and helpful Linux commands
#
# Files, folder and storage space
#
# Disk space and volumes:
lsblk | grep sd # List all disks
df -h | grep sd # Show volume size
# Find 15 biggest files in direcorty:
du -h /dir/name | sort -rh | head -n 15
# Find the size of a directory
du -sh /dir/name
# Clean files older than 14 days
find /dir/data/* -type d -ctime +14 -exec rm -rf {} \; 
# Count files in Dir
ls -1 | wc -l
# Without symlinks
ls -l | grep -v ^l | wc -l
# Find a specific string in all files:
grep -Rw String2 /etc/*
grep -rnw '/dir/with/the/files/' -e 'String1'
grep -Ril --exclude=\*.conf String3 /etc/* # Exclude files
# String Manipulation
sed -i 's/String1/String2/g' /dir/someScript.sh # Replace string1 with string2 within a text

# Shell adjustment
echo "Hello World" | colorize red black 5

# Monitoring and processes
free -m | grep Mem
ps auxf | grep SomePID

# Firewall and routing
netstat -tulpn | grep LISTEN # find all listening ports

iptables -L --line-numbers # Nice view for iptables rules

firewall-cmd --list-rich-rules # Nice view for firewalld rules
firewall-cmd --zone=public --list-ports
